from typing import Protocol, List, Optional
from memolink_backend.domain.models.note import Note
from memolink_backend.domain.models.embedding import Embedding


class INoteRepository(Protocol):
    def create_note(self, user_id: int, title: str | None, content: str, source: str | None) -> Note: ...
    def save_embedding(self, note_id: int, vector: list[float]) -> Embedding: ...
    def get_by_id(self, note_id: int) -> Optional[Note]: ...
    def get_for_user(self, user_id: int) -> List[Note]: ...
    def get_trash_for_user(self, user_id: int) -> List[Note]: ...
    def update_note(self, note_id: int, title: str | None, content: str | None) -> Optional[Note]: ...
    def delete_note(self, note_id: int) -> bool: ...
    def restore_note(self, note_id: int) -> bool: ...
    def permanent_delete_note(self, note_id: int) -> bool: ...
    def search_by_vector(self, query_vector: list[float], top_k: int = 5) -> List[Note]: ...
