from typing import Protocol, Optional, List
from memolink_backend.domain.models.workspace import Workspace


class IWorkspaceRepository(Protocol):
    def create(self, user_id: int, name: str, type: str, description: Optional[str], is_default: bool) -> Workspace: ...
    def get_by_id(self, workspace_id: int) -> Optional[Workspace]: ...
    def get_for_user(self, user_id: int) -> List[Workspace]: ...
    def get_active_for_user(self, user_id: int) -> Optional[Workspace]: ...
    def update(self, workspace_id: int, name: Optional[str], type: Optional[str], description: Optional[str]) -> Optional[Workspace]: ...
    def soft_delete(self, workspace_id: int) -> bool: ...
    def set_last_accessed(self, workspace_id: int) -> Optional[Workspace]: ...
    def count_active_for_user(self, user_id: int) -> int: ...
    def name_exists_for_user(self, user_id: int, name: str, exclude_id: Optional[int]) -> bool: ...
    def get_alert_count(self, workspace_id: int) -> int: ...
