from typing import Protocol
from memolink_backend.contracts.auth_dtos import RegisterDTO, LoginDTO, TokenResponse, ChangePasswordDTO, ForgotPasswordDTO, ResetPasswordDTO


class IAuthService(Protocol):
    def register(self, dto: RegisterDTO) -> TokenResponse: ...
    def login(self, dto: LoginDTO) -> TokenResponse: ...
    def change_password(self, user_id: int, dto: ChangePasswordDTO) -> None: ...
    def forgot_password(self, dto: ForgotPasswordDTO) -> None: ...
    def reset_password(self, dto: ResetPasswordDTO) -> None: ...
