from typing import Protocol, Any


class IConversationService(Protocol):
    def list_for_user(self, user_id: int) -> list[dict[str, Any]]: ...
    def list_trash(self, user_id: int) -> list[dict[str, Any]]: ...
    def create(self, user_id: int, title: str | None) -> dict[str, Any]: ...
    def get_messages_paginated(self, conv_id: int, limit: int, before_id: int | None) -> list[dict[str, Any]]: ...
    def rename(self, conv_id: int, title: str) -> dict[str, Any] | None: ...
    def delete(self, conv_id: int) -> bool: ...
    def restore_conversation(self, conv_id: int) -> bool: ...
    def permanent_delete_conversation(self, conv_id: int) -> bool: ...
    def delete_message(self, message_id: int) -> bool: ...
    def add_message_to_note(self, user_id: int, content: str, title: str | None) -> dict[str, Any]: ...
