from typing import Protocol, List, Any
from memolink_backend.contracts.note_dtos import NoteCreateDTO, NoteUpdateDTO, NoteResponseDTO


class INoteService(Protocol):
    def create_note(self, dto: NoteCreateDTO) -> NoteResponseDTO: ...
    def get_note(self, note_id: int) -> NoteResponseDTO | None: ...
    def list_notes(self, user_id: int) -> List[NoteResponseDTO]: ...
    def list_trash(self, user_id: int) -> List[dict[str, Any]]: ...
    def update_note(self, dto: NoteUpdateDTO) -> NoteResponseDTO | None: ...
    def delete_note(self, note_id: int) -> bool: ...
    def restore_note(self, note_id: int) -> bool: ...
    def permanent_delete_note(self, note_id: int) -> bool: ...
    def search_notes(self, vector: list[float], top_k: int) -> List[NoteResponseDTO]: ...
